package module;

public enum  DataType {

    /** Numeric */
    TINYINT, SMALLINT, MEDIUMINT, INT, BIGINT,

    DECIMAL, FLOAT, DOUBLE, REAL,

    BIT, BOOLEAN, SERIAL,

    /** Date and Time */
    DATE, DATETIME, TIMESTAMP, TIME, YEAR,

    /** String */
    CHAR, VARCHAR,

    TINYTEXT, MEDIUMTEXT, TEXT, LONGTEXT,

    BINARY, VARBINARY,

    TINYBLOB, MEDIUMBLOB, BLOB, LONGBLOB,

    ENUM,SET,

    /** Spatial */
    GEOMETRY, POINT, LINESTRING, POLYGON, MULTIPOINT, MULTILINESTRING, MULTIPOLYGON, GEOMETRYCOLLECTION

}
